#!/bin/sh

# This file allows one to compile and produce an ARM assembly listing for the mbed LPC1768
# ./assemble.sh -S <source files>

INCLUDE_PATHS=""
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/TARGET_LPC1768"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/TARGET_LPC1768/TARGET_NXP"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/TARGET_LPC1768/TARGET_NXP/TARGET_LPC176X"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/TARGET_LPC1768/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/TARGET_LPC1768/TARGET_NXP/TARGET_LPC176X/device"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/TARGET_LPC1768/TOOLCHAIN_GCC_ARM"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/drivers"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/hal"
INCLUDE_PATHS="$INCLUDE_PATHS -Imbed/platform"

FLAGS=""
FLAGS="$FLAGS -fno-rtti"
FLAGS="$FLAGS -Wvla"
FLAGS="$FLAGS -DDEVICE_ERROR_PATTERN=1"
FLAGS="$FLAGS -DMBED_BUILD_TIMESTAMP=1490189006.28"
FLAGS="$FLAGS -D__MBED__=1"
FLAGS="$FLAGS -DDEVICE_I2CSLAVE=1"
FLAGS="$FLAGS -DTARGET_LIKE_MBED"
FLAGS="$FLAGS -DTARGET_NXP"
FLAGS="$FLAGS -DTARGET_LPC176X"
FLAGS="$FLAGS -D__MBED_CMSIS_RTOS_CM"
FLAGS="$FLAGS -DDEVICE_RTC=1"
FLAGS="$FLAGS -DTOOLCHAIN_object"
FLAGS="$FLAGS -D__CMSIS_RTOS"
FLAGS="$FLAGS -DFEATURE_LWIP=1"
FLAGS="$FLAGS -DTOOLCHAIN_GCC"
FLAGS="$FLAGS -DDEVICE_CAN=1"
FLAGS="$FLAGS -DTARGET_LIKE_CORTEX_M3"
FLAGS="$FLAGS -DTARGET_CORTEX_M"
FLAGS="$FLAGS -DARM_MATH_CM3"
FLAGS="$FLAGS -DDEVICE_ANALOGOUT=1"
FLAGS="$FLAGS -DTARGET_UVISOR_UNSUPPORTED"
FLAGS="$FLAGS -DTARGET_M3"
FLAGS="$FLAGS -DDEVICE_PWMOUT=1"
FLAGS="$FLAGS -DDEVICE_INTERRUPTIN=1"
FLAGS="$FLAGS -DTARGET_LPCTarget"
FLAGS="$FLAGS -DDEVICE_I2C=1"
FLAGS="$FLAGS -DDEVICE_PORTOUT=1"
FLAGS="$FLAGS -D__CORTEX_M3"
FLAGS="$FLAGS -DDEVICE_STDIO_MESSAGES=1"
FLAGS="$FLAGS -DTARGET_LPC1768"
FLAGS="$FLAGS -DTARGET_RELEASE"
FLAGS="$FLAGS -DDEVICE_PORTINOUT=1"
FLAGS="$FLAGS -DDEVICE_SERIAL_FC=1"
FLAGS="$FLAGS -DTARGET_MBED_LPC1768"
FLAGS="$FLAGS -DDEVICE_PORTIN=1"
FLAGS="$FLAGS -DDEVICE_SLEEP=1"
FLAGS="$FLAGS -DTOOLCHAIN_GCC_ARM"
FLAGS="$FLAGS -DDEVICE_SPI=1"
FLAGS="$FLAGS -DDEVICE_ETHERNET=1"
FLAGS="$FLAGS -DDEVICE_SPISLAVE=1"
FLAGS="$FLAGS -DDEVICE_ANALOGIN=1"
FLAGS="$FLAGS -DDEVICE_SERIAL=1"
FLAGS="$FLAGS -DDEVICE_SEMIHOST=1"
FLAGS="$FLAGS -DDEVICE_DEBUG_AWARENESS=1"
FLAGS="$FLAGS -DDEVICE_LOCALFILESYSTEM=1"
FLAGS="$FLAGS -include"
FLAGS="$FLAGS mbed_config.h"

CC='arm-none-eabi-gcc -std=gnu99 -c -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -O5 -mcpu=cortex-m3 -mthumb'
$CC $FLAGS $INCLUDE_PATHS $1 $2 $3 $4 $5 $6

# For C++ use the following:
#CPP='arm-none-eabi-g++ -std=gnu++98 -fno-rtti -Wvla -c -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -O5 -mcpu=cortex-m3 -mthumb'
#$CPP $FLAGS $INCLUDE_PATHS $1 $2 $3 $4 $5 $6

