#!/bin/bash
wget https://opensource.apple.com/tarballs/diskdev_cmds/diskdev_cmds-332.14.tar.gz
wget http://gentoo.osuosl.org/distfiles/diskdev_cmds-332.14_p1.patch.bz2
bunzip2 -c diskdev_cmds-332.14_p1.patch.bz2 | patch -p0
cd diskdev_cmds-332.14
make -f Makefile.lnx
sudo cp fsck_hfs.tproj/fsck_hfs /sbin/fsck.hfsplus
sudo cp newfs_hfs.tproj/newfs_hfs /sbin/mkfs.hfsplus
sudo apt-get install hfsplus
cd ..
rm -rf diskdev_cmds-332.14
rm diskdev_cmds-332.14.tar.gz
rm diskdev_cmds-332.14_p1.patch.bz2
